### ISSUE TITLE
spin_test.py unexpected behavior?

### ISSUE THREAD

**Issue by bohan-li** [deepmind/spectral_inference_networks#2]
Hi, I'm was running spin_test.py to get a basic understanding for how spin works and I noticed that it seems to be consistently finding the smallest magnitude eigenvalues rather than the largest. Is this expected behavior? I thought the paper specified that the goal of spin was to find the top N eigenfunctions? If it is expected behavior, is there a way to reverse the problem formulation to get the largest rather than smallest?

I was running spin_test with random seed 0 with matrices of size 10, and finding 5 eigenfunctions.

Actual eigenvalues:
![image](https://user-images.githubusercontent.com/27116406/108198805-528b3100-70d9-11eb-879d-760b54e75a1d.png)

Calculated eigenvalues:
![image](https://user-images.githubusercontent.com/27116406/108198911-78b0d100-70d9-11eb-9518-e650bd452c50.png)

**Comment by dpfau** [comment]
It is meant to find the smallest, not largest. You could simply put a minus
sign in front of the loss to get the largest. While this will work fine for
finite matrices, I would not recommend it for linear operators (and I would
not recommend using SpIN for finite matrices for anything other than sanity
checks).

**Comment by bohan-li** [comment]
Thank you for your quick response!
